config/routes.rb
Appenings::Application.routes.draw do
  devise_for :users

  get "login/index"

  resources :friends do
    get :add, :on => :member
    get :remove, :on => :member
  end

  resources :appenings do
    get :story, :on => :member
    get :cancel, :on => :collection
    get :feed, :on => :collection
    post :accomplish, :on => :member
    post :copy, :on => :member
    resources :comments do
      get :cancel, :on => :collection
    end
    resources :pictures do
      post :upload, :on => :collection
      post :remove, :on => :member
    end
  end

  root :to => "login#index"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
  end

  match "feed" => "feed#show"
  match "remove_feed/:appening_id" => "feed#remove"

end

app/models/appening.rb
class Appening
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :accomplished, type: Boolean, default: false
  field :public, type: Boolean, default: true
  field :story, type: String
  embeds_many :pictures  
  validates_presence_of :title, :user

  belongs_to :user, foreign_key: :user_id
  embeds_many :comments
end

app/controllers/appenings_controller.rb
class AppeningsController < ApplicationController
  # GET /appenings
  # GET /appenings.json
  def index
    @appenings = current_user.appenings.where(accomplished: false).sort("created_at desc")
    @accomplished_appenings = current_user.appenings.where(accomplished: true).sort("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @appenings }
    end
  end

  # GET /appenings/1
  # GET /appenings/1.json
  def show
    @appening = Appening.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appening }
    end
  end

  # GET /appenings/new
  # GET /appenings/new.json
  def new
    @appening = Appening.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  # GET /appenings/1/edit
  def edit
    @appening = current_user.appenings.find(params[:id])
  end

  # POST /appenings
  # POST /appenings.json
  def create
    @appening = Appening.new(params[:appening])
    @appening.user = current_user

    respond_to do |format|
      if @appening.save
        content = @appening.title
        feed_event = FeedEvent.create(user: current_user, content: content, type: "appening")
        current_user.friends.each do |friend_id|
          friend = User.find(friend_id)
          friend.feed_events << feed_event.id 
          friend.save
        end
        format.html { redirect_to "/appenings/", notice: 'Appening was successfully created.' }
        format.json { render json: @appening, status: :created, location: @appening }
      else
        format.html { redirect_to "/appenings/", alert: 'Appening could not be created, need content.' }
        format.json { render json: @appening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /appenings/1
  # PUT /appenings/1.json
  def update
    @appening = Appening.find(params[:id])

    respond_to do |format|
      if @appening.update_attributes(params[:appening])
        format.html { redirect_to appenings_path, notice: 'Appening was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appenings/1
  # DELETE /appenings/1.json
  def destroy
    @appening = Appening.find(params[:id])
    @appening.destroy

    respond_to do |format|
      format.html { redirect_to appenings_url }
      format.json { head :no_content }
    end
  end

  def accomplish
    @appening = Appening.find(params[:id])
    @appening.accomplished = !@appening.accomplished
    @appening.save
    if @appening.accomplished
      flash.notice = "Congratulations, you've accomplished a goal!"
    else
      flash.notice = "Undid accomplishment (story and pictures will still be available)."
    end
    redirect_to appenings_path
  end

  def copy
    @appening = Appening.find(params[:id])
    copy_appening = @appening.dup
    copy_appening.comments.delete_all
    copy_appening.pictures.delete_all
    copy_appening.accomplished = false
    current_user.appenings << copy_appening
    redirect_to appenings_path, notice: "Good luck!"
  end

  def cancel
    @appening = Appening.find(params[:appening_id]) rescue nil
    @original_action = params[:original_action]

    respond_to do |format|
      format.js
    end
  end

  def story
    @appening = Appening.find(params[:id])
    
    respond_to do |format|
      format.js
    end
  end

  def feed
    @friends = current_user.friends.map {|friend| User.find(friend)}
    @appenings = @friends.map do |friend|
      friend.appenings.last
    end
  end
end

app/helpers/appenings_helper.rb
module AppeningsHelper
end

app/views/appenings/_accomplished.html.erb
<div class="span6">
  <div class="well">
    <div id="appening_<%= appening.id %>">
      <h4 style="display:inline;"><%= appening.title %></h4>  
      <i class='icon-chevron-up pull-right'></i>
    </div>
    <div class="appeningDetails">
      <div class="row">
        <%= link_to "Share your story", story_appening_path(appening), remote: true %>
        <%= link_to "Unaccomplish", accomplish_appening_path(appening), method: "post" %>
        <%= link_to "Comment", new_appening_comment_path(appening_id: appening.id), remote: true%>
        <%= link_to "Delete", appening_path(appening), method: "delete", confirm: "Are you sure?"%>
      </div>

      <p class="story"><%= appening.story %></p>

      <div class="row"> <!-- CAROUSEL ON CLICK? FANCYBOX?? -->
        <% appening.pictures.each do |picture| %>
        <%= image_tag picture.attachment.url(:medium) %>
        <%= link_to "Remove", remove_appening_picture_path(picture, appening_id: appening), method: "post" %>
        <% end %>
      </div>

      <div class="row">
        <b>Upload picture:</b>
        <%= form_for appening, url: upload_appening_pictures_path(appening_id: appening.id), html: { method: "post"} do |f| %>
        <%= f.file_field :attachment %>
        <%= f.submit "Upload" %>
        <% end %>
      </div>
      <div id="comment_container_<%= appening.id %>" class="comment_container"></div>
      <div class="row">
        <% appening.comments.each do |comment| %> 
          <div class="comments">
            <b><%= comment.author %> wrote: </b>
            <p><%= comment.text %></p>
            <%= link_to "Delete", appening_comment_path(appening, comment), method: "delete", confirm: "Are you sure?" if comment.author == current_user.username %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/appenings/_appening.html.erb
<div class="span6">
  <div class="well">
    <div id="appening_<%= appening.id %>">
      <h4 style="display:inline;"><%= appening.title %></h4>  
      <i class='icon-chevron-up pull-right'></i>
    </div>
    <div class="appeningDetails">
      <%= link_to "<i class='icon-ok'></i>".html_safe, accomplish_appening_path(appening), method: :post, id: "accomplish_appening" %>
      <%= link_to "<i class='icon-remove'></i>".html_safe, appening_path(appening), method: "delete", confirm: "Are you sure?", id: "delete_appening" %>
      <p><%= appening.created_at.strftime("%D") %></p>
      <%= link_to "<i class='icon-pencil'></i>".html_safe, edit_appening_path(appening), remote: true %>
      <%= link_to "<i class='icon-comment-alt'></i>".html_safe, new_appening_comment_path(appening_id: appening.id), class: "comment-appening", remote: true %>
      <div id="comment_container_<%= appening.id %>" class="comment_container"></div>
      <% appening.comments.each do |comment| %> 
        <div class="comments">
          <%= comment.author %> wrote: 
          <%= comment.text %>
          <%= link_to "Delete", appening_comment_path(appening, comment), method: "delete", confirm: "Are you sure?" if comment.author == current_user.username %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/appenings/_form.html.erb
<div class="appening_form_container">
	<%= form_for(@appening) do |f| %>
	<div id= "appening_new " class="newAppening grid_14 alpha">
		<%= f.text_field :title, autocomplete: "off", id: "#{params[:action]}_appening_field", placeholder: "What do you want to accomplish?" %>
	</div>
  Public: <%= f.check_box :public %>
	<%= link_to "<i class='icon-ok grid_1'></i>".html_safe, "#", :class => "submit", id: "submit_appening" %>
	<%= link_to "<i class='icon-remove grid_1 omega'></i>".html_safe, cancel_appenings_path(appening_id: @appening, original_action: params[:action]), remote: true, :id => "cancelAppening" %>
	<% end %>
</div>

app/views/appenings/_story.html.erb
<div class="comment_form_container">
<%= form_for(@appening) do |f| %>
  <h4> Tell your story </h4>
  <span class="cancellNewAppening">
  </span>
  <%= f.text_area :story, id: "new_story", autofocus: true, size: "40x8" %>
  <%= link_to "<i class='icon-remove'></i>".html_safe, cancel_appening_comments_path(appening_id: @appening, original_action: params[:action]), remote: true %>
  <%= f.submit "Save story" %>
  <% end %>
</div>

app/views/appenings/cancel.js.erb
<% if @original_action == "edit" %>
  $("#appening_<%= @appening.id %>").html("<h4><%= @appening.title %></h4>");
<% else %>
  $("#newAppening").html("");
  $('#newAppening').slideToggle('slow');
<% end %>

app/views/appenings/edit.js.erb
$(".appening_form_container").html("");
$("#appening_<%= @appening.id %>").html("<%= escape_javascript( render partial: "form" ) %>");
$("#edit_appening_field").focus();

app/views/appenings/feed.html.erb
<h3>Friend feed</h3>
<% @appenings.each do |appening| %>
  <div class="grid_16">
    <%= appening.user.username %> posted <%= appening.title %>
  </div>
  <div class="clear"></div>
  <div id="comment_container_<%= appening.id %>" class="comment_container grid_16"></div>
  <%= button_to "Comment", new_appening_comment_path(appening_id: appening.id), method: "get", remote: true, class: "grid_2 alpha" %> 
  <%= button_to "Copy", copy_appening_path(appening, user_id: appening.user.id), class: "grid_2 omega" %>
  
<% end %>

app/views/appenings/index.html.erb
<h3>Appenings</h3>
<%= link_to "new <i class='icon-plus'></i>".html_safe, new_appening_path, :class => "newAppeningButton", remote: true %>
<div id="newAppening" class="appening"></div>

<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Incomplete</a></li>
    <li><a href="#tab2" data-toggle="tab">Complete</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <% @appenings.each do |appening| %>
        <%= render appening %>
      <% end %>
    </div>
    <div class="tab-pane" id="tab2">
      <% @accomplished_appenings.each do |appening| %>
        <%= render :partial => "accomplished", locals: {appening: appening} %>
      <% end %>
    </div>
  </div>
</div>

app/views/appenings/new.js.erb
if($('#newAppening').is(":visible")){
	$(".appening_form_container").html("");
	$("#newAppening").html("<%= escape_javascript( render partial: "form" ) %>");
	$("#new_appening_field").focus();
} else {
	//it's visible, do nothing
}

app/views/appenings/show.html.erb
<p>
  <b>Title:</b>
  <%= @appening.title %>
</p>


<%= link_to 'Edit', edit_appening_path(@appening) %> |
<%= link_to 'Back', appenings_path %>

app/views/appenings/story.js.erb
$(".comment_container").html("");
$("#comment_container_<%= @appening.id %>").html("<%= escape_javascript( render partial: "story") %>");