config/routes.rb
Appenings::Application.routes.draw do
  devise_for :users

  get "login/index"

  resources :friends do
    get :add, :on => :member
    get :remove, :on => :member
  end

  resources :appenings do
    get :story, :on => :member
    get :cancel, :on => :collection
    get :feed, :on => :collection
    post :accomplish, :on => :member
    post :copy, :on => :member
    resources :comments do
      get :cancel, :on => :collection
    end
    resources :pictures do
      post :upload, :on => :collection
      post :remove, :on => :member
    end
  end

  root :to => "login#index"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
  end

  match "feed" => "feed#show"
  match "remove_feed/:appening_id" => "feed#remove"

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = current_user.friends.map {|friend_id| User.find(friend_id)}
  end

  def new
    @users = User.where(:id.ne => current_user.id)

    respond_to do |format|
      format.html
    end
  end

  def add
    @friend = User.find(params[:id])
    current_user.friends << @friend.id
    current_user.save

    redirect_to friends_path, notice: "#{@friend.username} added as a friend."
  end

  def remove
    @friend = User.find(params[:id])
    current_user.friends.delete(@friend.id)
    current_user.save
    
    redirect_to friends_path, notice: "#{@friend.username} removed as friend."
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<div class="grid_16">
  <h1>Browse friends</h1>
</div>
<div class="appeningEntries">
  <% @friends.each do |friend| %>
    <div class="friends">
      <h4 class="grid_8 alpha"><%= friend.username %></h4>
      <div class="grid_2 omega"><%= link_to "[remove]", remove_friend_path(friend), confirm: "Are you sure you want to remove #{friend.username} as a friend?" %></div>
      <div class="clear"></div>
      <% friend.appenings.each do |appening| %>
        <div class="appening">
          <% if appening.public %>
            <div class="friend-details grid_16">
              <h5 class="grid_16"><%= appening.title %></h5>
              <%= appening.accomplished ? "Accomplished" : "In progress" %>
              <div class="clear"></div>
              <%= button_to "Comment", new_appening_comment_path(appening_id: appening.id), method: "get", remote: true, class: "grid_2 alpha" %> 
              <%= button_to "Copy", copy_appening_path(appening, user_id: friend.id), class: "grid_2 omega" %>
              <div id="comment_container_<%= appening.id %>" class="comment_container grid_16"></div>
              <% appening.comments.each do |comment| %> 
                <div class="comments grid_8">
                  <b><%= comment.author %> wrote: </b>
                  <p><%= comment.text %></p>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<hr/>
<div class="clear"></div>
<div class="grid_16 alpha">
  <%= link_to "Add new friend", new_friend_path, class: "grid_2 alpha" %> 
  <%= link_to "Back", appenings_path, class: "grid_2 omega" %>
</div>

app/views/friends/new.html.erb
<h1>Add friend</h1>

<% @users.each do |user| %>
  <div class="friends">
    <%= user.username %>
    <%= link_to("Add friend", add_friend_path(user)) unless current_user.friends.include?(user.id) %>
  </div>
<% end %>
<br/>
<%= link_to "Back", friends_path %>