config/routes.rb
Appenings::Application.routes.draw do
  devise_for :users

  get "login/index"

  resources :friends do
    get :add, :on => :member
    get :remove, :on => :member
  end

  resources :appenings do
    get :story, :on => :member
    get :cancel, :on => :collection
    get :feed, :on => :collection
    post :accomplish, :on => :member
    post :copy, :on => :member
    resources :comments do
      get :cancel, :on => :collection
    end
    resources :pictures do
      post :upload, :on => :collection
      post :remove, :on => :member
    end
  end

  root :to => "login#index"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
  end

  match "feed" => "feed#show"
  match "remove_feed/:appening_id" => "feed#remove"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Appenings</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
      <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="nav-collapse collapse">
          <% if current_user.present? %>
            <%= link_to "Appenings", appenings_path, class: "brand" %>
            <ul class="nav">
              <li><%= link_to "Feed", feed_path %></li>
              <li><%= link_to "<i class='icon-group'></i>".html_safe, friends_path, :class => "friendButton" %></li>
              <li><%= link_to "<i class='icon-signout'></i>".html_safe, logout_path, :id => "logout", :class => "logoutButton" %></li>
            </ul>
          <% else %>
            <span class="brand">Appenings</span>
          <% end %>
        </div>
      </div>
		</div>
	</div>

	<div class="container">
		<%= yield %>
	</div>
	<% if notice.present? %>
		<div class="notice"><p><%= notice %></p></div>
		<% end %>

		<% if alert.present? %>
		<div class="alert"><p><%= alert %></p></div>
		<% end %>
</body>
</html>